# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.GenericUser')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('artist_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistAudio')),
            ],
        ),
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female'), (b'Male & Female', b'Male & Female')], max_length=50)),
                ('language', models.CharField(choices=[(b'Afrikaans', b'Afrikaans'), (b'Arabic', b'Arabic'), (b'Albenian', b'Albenian'), (b'Bahasa-Indonesian', b'Bahasa-Indonesian'), (b'Bahasa-Malaysian', b'Bahasa-Malaysian'), (b'Bengali', b'Bengali'), (b'Bosnian', b'Bosnian'), (b'Bulgarian', b'Bulgarian'), (b'Cambodian', b'Cambodian'), (b'Caribbean', b'Caribbean'), (b'Catalan', b'Catalan'), (b'Chinese-Cantonese', b'Chinese-Cantonese'), (b'Chinese-Mandrin', b'Chinese-Mandrin'), (b'Croatian', b'Croatian'), (b'czech', b'czech'), (b'Danish', b'Danish'), (b'Dutch', b'Dutch'), (b'English-Indian', b'English-Indian'), (b'English-US', b'English-US'), (b'English-UK', b'English-UK'), (b'English-AustralianEnglish-Latin American', b'English-AustralianEnglish-Latin American'), (b'English-South African', b'English-South African'), (b'English-Asian', b'English-Asian'), (b'Finnish,Flemish,', b'Finnish,Flemish,'), (b'French-Canadian', b'French-Canadian'), (b'French-European', b'French-European'), (b'Georgeon', b'Georgeon'), (b'German', b'German'), (b'Greek', b'Greek'), (b'Gujarati', b'Gujarati'), (b'Hebrew', b'Hebrew'), (b'Hindi', b'Hindi'), (b'Hungarian', b'Hungarian'), (b'Icelandic', b'Icelandic'), (b'Indonesian', b'Indonesian'), (b'Italian', b'Italian'), (b'Irish', b'Irish'), (b'Japanese', b'Japanese'), (b'Kannada', b'Kannada'), (b'Korean', b'Korean'), (b'Kurdish', b'Kurdish'), (b'Latvian', b'Latvian'), (b'Malayalam', b'Malayalam'), (b'Marathi', b'Marathi'), (b'Maltese', b'Maltese'), (b'Malay', b'Malay'), (b'Norwegian', b'Norwegian'), (b'Oriya', b'Oriya'), (b'Persian', b'Persian'), (b'Polish', b'Polish'), (b'Portugese-Brazil', b'Portugese-Brazil'), (b'Portugese-Europe', b'Portugese-Europe'), (b'Punjabi', b'Punjabi'), (b'Romanian', b'Romanian'), (b'Russian', b'Russian'), (b'Sanskrit', b'Sanskrit'), (b'Serbian', b'Serbian'), (b'Slovak', b'Slovak'), (b'Slovanian', b'Slovanian'), (b'Spanish-Latin American', b'Spanish-Latin American'), (b'Spanish-Europe', b'Spanish-Europe'), (b'Swahili', b'Swahili'), (b'Swedish', b'Swedish'), (b'Tagalog', b'Tagalog'), (b'Tamil', b'Tamil'), (b'Telugu', b'Telugu'), (b'Thai', b'Thai'), (b'Turkish', b'Turkish'), (b'Urudu', b'Urudu'), (b'Ukranian', b'Ukranian'), (b'Vietnamese', b'Vietnamese')], max_length=50)),
                ('age_range', models.CharField(choices=[(b'Teenage', b'Teenage'), (b'Young Adult', b'Young Adult'), (b'Middle Age', b'Middle Age'), (b'Senior', b'Senior')], max_length=50)),
                ('voice_over_type', models.CharField(choices=[(b'Radio & TV Commercials', b'Radio & TV Commercials'), (b'Infomercials & Explainer Videos', b'Infomercials & Explainer Videos'), (b'Corporate Videos & Presentations', b'Corporate Videos & Presentations'), (b'Cartoon/Animation Videos', b'Cartoon/Animation Videos'), (b'Documentaries', b'Documentaries'), (b'Audio-books', b'Audio-books'), (b'IVR', b'IVR')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('artist_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.ArtistAudio')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Commercial', b'Commercial'), (b'Infomercials & Explainer Videos', b'Infomercials & Explainer Videos'), (b'Corporate Videos & Presentations', b'Corporate Videos & Presentations'), (b'Cartoon / Animation Videos', b'Cartoon / Animation Videos'), (b'Documentaries', b'Documentaries'), (b'Audio-books', b'Audio-books'), (b'IVR', b'IVR')], max_length=50)),
                ('duration_in_minutes', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('script_text', models.CharField(max_length=1000)),
                ('script_url', models.URLField()),
                ('additional_notes', models.CharField(max_length=500)),
                ('has_characters', models.BooleanField(default=False)),
                ('reference_file_url', models.URLField()),
                ('audio_book_name', models.CharField(max_length=200)),
                ('ivr_count', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Request'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Request'),
        ),
        migrations.AddField(
            model_name='artistaudio',
            name='audio_clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.AudioClip'),
        ),
    ]
