# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170414_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
    ]
